In [2]:
!pip install netifaces

  Using cached netifaces-0.11.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_ext
      checking for getifaddrs...not found.
      checking for getnameinfo...not found.
      checking for socket IOCTLs...not found.
      checking for optional header files...none found.
      checking whether struct sockaddr has a length field...no.
      checking which sockaddr_xxx structs are defined...none!
      checking for routing socket support...no.
      checking for sysctl(CTL_NET...) support...no.
      checking for netlink support...no.
      building 'netifaces' extension
      gcc -pthread -B /home/b202301931/anaconda3/envs/py10/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/b202301931/anaconda3/envs/py10/include -fPIC -

In [6]:
import os
import sys
import uuid
from netifaces import interfaces, ifaddresses, AF_INET

print(os.getlogin())
print(sys.version)

for ifaceName in interfaces():
    addresses = [i['addr'] for i in ifaddresses(ifaceName).setdefault(AF_INET, [{'addr':'No IP addr'}] )]
    print('%s: %s' % (ifaceName, ', '.join(addresses)))

print ('MAC:',':'.join(['{:02x}'.format((uuid.getnode() >> ele) & 0xff)
for ele in range(0,8*6,8)][::-1]))


b202301931
3.9.20 (main, Oct  3 2024, 07:27:41) 
[GCC 11.2.0]
lo: 127.0.0.1
enp0s3: 192.168.200.124
MAC: 6f:b7:fd:f1:21:3c


In [3]:
!pip install numpy

In [5]:
import numpy as np


a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
pip install module_name

Note: you may need to restart the kernel to use updated packages.
